### PR TITLE
chore(package): map TS types explicitly

### PR DESCRIPTION
**Pull request by char0n**
Refs #46

This PR is alternative approach to https://github.com/jeanlescure/short-unique-id/pull/46

### CODE REVIEW

**Comment by ColdtQ** [comment]
> Refs #46
> 
> 
> 
> This PR is alternative approach to https://github.com/jeanlescure/short-unique-id/pull/46

I'm going to close my PR, this is a much better solution.

**Comment by ColdtQ** [comment]
@char0n Can you request a review from maintainer?

**Comment by ColdtQ** [comment]
@jeanlescure

**Comment by char0n** [comment]
@ColdtQ I’d say I already did by issuing this PR :)

**Comment by jeanlescure** [comment]
Thanks for the contribution @char0n and @ColdtQ ! 🚀 

I tested further and found the following case where types were being inferred rather than being defined by the `.d.ts`:

Screenshot_20210829_143403

Changing the build so that the `.d.ts` file matches the name of the output `.js` file solves this issue:

Screenshot_20210829_143530

I feel silly for not having noticed that the generated `.d.ts` filename did not match the library's output `.js` file 😅

**Pull request merged**
