### PR TITLE
Removed uncommon syntax for post-processors

### PR DESCRIPTION
**Pull request by jeffturcotte**
Re: #1, while this is technically an uglify issue (and apparently fixed in some newer versions?), the issue is with the use of an object property as the index variable in a for-in loop. Maybe there was a programmatic reason for this in an earlier version of this lib? I saw no reason to keep it as is. Altering the syntax to something more common fixed the uglify processing issue for me.

In my case, I'm dependent on a 3rd party build tool that is itself dependent on a certain version of uglify. Upgrading uglify would not be convenient, so I hope you accept this change.

Thanks for the great lib!

### CODE REVIEW

**Comment by jeanlescure** [comment]
Hi @jeffturcotte, your PR looks promising!

Could you please provide me with the version of uglify that's causing all this fuzz?

I'll more than gladly merge your work after testing against said version 👍 

Cheers!

**Comment by jeffturcotte** [comment]
Upon further review, the problem is technically with any pre-1.0.0 version of uglifyjs-webpack-plugin and not uglify itself.

IMO, the fix is stylistically better than what is in there now from the older forked lib. So it's an improvement either way. Thanks.

**Comment by jeanlescure** [comment]
@jeffturcotte, I agree the fix is stylistically better. I was just really curious to have a test case; do excuse my OCD.

I'll be merging soon and publishing `v1.1.1` 👍

**Comment by jeanlescure** [comment]
Tested against `uglifyjs-webpack-plugin v0.4.6`, both bug and fix confirmed. Moving forward with merge.

**Pull request merged**
